Traceback (most recent call last):
  File "downloaderscript.py", line 26, in <module>
    startdate=sys.argv[1] 
IndexError: list index out of range
